In [1]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/python/3.12.1/lib/python3.12/site-packages (3.0.1)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from pandas) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/codespace/.local/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/codespace/.local/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd

# Load dataset
df = pd.read_csv("Unemployment Data.csv")

# Clean column names
df.columns = df.columns.str.strip().str.lower()

# Clean county column (remove extra spaces)
df['county'] = df['county'].str.strip()

# Add " County" to the end of each county name
df['county'] = df['county'] + " County"

# Save updated file
df.to_csv("Unemployment_Data_Updated.csv", index=False)

print("Successfully added 'County' to all county names.")
print(df['county'].head())

Successfully added 'County' to all county names.
0    Alameda County
1    Alameda County
2    Alameda County
3    Alameda County
4    Alameda County
Name: county, dtype: str

In [3]:
import pandas as pd

# Load dataset
df = pd.read_csv("crime.csv")

# Clean column names
df.columns = df.columns.str.strip().str.lower()

# Make sure month column is numeric
df['month'] = pd.to_numeric(df['month'], errors='coerce')

# Convert month number to month name
df['month'] = pd.to_datetime(df['month'], format='%m', errors='coerce').dt.month_name()

# Save updated file
df.to_csv("crime_updated.csv", index=False)

print("Month numbers successfully converted to month names.")
print(df['month'].head())

/tmp/ipykernel_7589/3640051333.py:4: DtypeWarning: Columns (0: Violent_sum, 1: Homicide_sum, 2: ForRape_sum, 3: Robbery_sum, 4: AggAssault_sum, 5: Property_sum, 6: Burglary_sum, 7: VehicleTheft_sum, 8: LTtotal_sum, 9: ViolentClr_sum, 10: HomicideClr_sum, 11: ForRapeClr_sum, 12: RobberyClr_sum, 13: AggAssaultClr_sum, 14: PropertyClr_sum, 15: BurglaryClr_sum, 16: VehicleTheftClr_sum, 17: LTtotalClr_sum, 18: TotalStructural_sum, 19: TotalMobile_sum, 20: TotalOther_sum, 21: GrandTotal_sum, 22: GrandTotClr_sum, 23: RAPact_sum, 24: ARAPact_sum, 25: FROBact_sum, 26: KROBact_sum, 27: OROBact_sum, 28: SROBact_sum, 29: HROBnao_sum, 30: CHROBnao_sum, 31: GROBnao_sum, 32: CROBnao_sum, 33: RROBnao_sum, 34: BROBnao_sum, 35: MROBnao_sum, 36: FASSact_sum, 37: KASSact_sum, 38: OASSact_sum, 39: HASSact_sum, 40: FEBURact_Sum, 41: UBURact_sum, 42: RESDBUR_sum, 43: RNBURnao_sum, 44: RDBURnao_sum, 45: RUBURnao_sum, 46: NRESBUR_sum, 47: NNBURnao_sum, 48: NDBURnao_sum, 49: NUBURnao_sum, 50: MVTact_sum, 51: TMVTact_sum, 52: OMVTact_sum, 53: PPLARnao_sum, 54: PSLARnao_sum, 55: SLLARnao_sum, 56: MVLARnao_sum, 57: MVPLARnao_sum, 58: BILARnao_sum, 59: FBLARnao_sum, 60: COMLARnao_sum, 61: AOLARnao_sum, 62: LT400nao_sum, 63: LT200400nao_sum, 64: LT50200nao_sum, 65: LT50nao_sum) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("crime.csv")

Month numbers successfully converted to month names.
0    January
1    January
2    January
3    January
4    January
Name: month, dtype: str

In [4]:
import pandas as pd

# Load the datasets
crime_df = pd.read_csv("crime_updated.csv")
unemployment_df = pd.read_csv("Unemployment_Data_Updated.csv")

# Optional: Standardize column names (lowercase + strip spaces)
crime_df.columns = crime_df.columns.str.strip().str.lower()
unemployment_df.columns = unemployment_df.columns.str.strip().str.lower()

# Optional: Clean merge key columns (remove extra spaces, standardize case)
for col in ['year', 'county', 'month']:
    crime_df[col] = crime_df[col].astype(str).str.strip().str.lower()
    unemployment_df[col] = unemployment_df[col].astype(str).str.strip().str.lower()

# Merge the datasets
merged_df = pd.merge(
    crime_df,
    unemployment_df,
    on=['year', 'month', 'county'],
    how='inner'   # change to 'left' if you want to keep all crime records
)

# Save the merged file
merged_df.to_csv("merged_output.csv", index=False)

print("Merge complete.")
print("Merged dataset shape:", merged_df.shape)
merged_df.head()

/tmp/ipykernel_7589/2143413297.py:4: DtypeWarning: Columns (0: violent_sum, 1: homicide_sum, 2: forrape_sum, 3: robbery_sum, 4: aggassault_sum, 5: property_sum, 6: burglary_sum, 7: vehicletheft_sum, 8: lttotal_sum, 9: violentclr_sum, 10: homicideclr_sum, 11: forrapeclr_sum, 12: robberyclr_sum, 13: aggassaultclr_sum, 14: propertyclr_sum, 15: burglaryclr_sum, 16: vehicletheftclr_sum, 17: lttotalclr_sum, 18: totalstructural_sum, 19: totalmobile_sum, 20: totalother_sum, 21: grandtotal_sum, 22: grandtotclr_sum, 23: rapact_sum, 24: arapact_sum, 25: frobact_sum, 26: krobact_sum, 27: orobact_sum, 28: srobact_sum, 29: hrobnao_sum, 30: chrobnao_sum, 31: grobnao_sum, 32: crobnao_sum, 33: rrobnao_sum, 34: brobnao_sum, 35: mrobnao_sum, 36: fassact_sum, 37: kassact_sum, 38: oassact_sum, 39: hassact_sum, 40: feburact_sum, 41: uburact_sum, 42: resdbur_sum, 43: rnburnao_sum, 44: rdburnao_sum, 45: ruburnao_sum, 46: nresbur_sum, 47: nnburnao_sum, 48: ndburnao_sum, 49: nuburnao_sum, 50: mvtact_sum, 51: tmvtact_sum, 52: omvtact_sum, 53: pplarnao_sum, 54: pslarnao_sum, 55: sllarnao_sum, 56: mvlarnao_sum, 57: mvplarnao_sum, 58: bilarnao_sum, 59: fblarnao_sum, 60: comlarnao_sum, 61: aolarnao_sum, 62: lt400nao_sum, 63: lt200400nao_sum, 64: lt50200nao_sum, 65: lt50nao_sum) have mixed types. Specify dtype option on import or set low_memory=False.
  crime_df = pd.read_csv("crime_updated.csv")

Merge complete.
Merged dataset shape: (127396, 75)

,year,county,nciccode,month,violent_sum,homicide_sum,forrape_sum,robbery_sum,aggassault_sum,property_sum,...,aolarnao_sum,lt400nao_sum,lt200400nao_sum,lt200nao_sum,lt50200nao_sum,lt50nao_sum,labor force,employment,unemployment,unemp. rate
0,2010,san bernardino county,Adelanto,january,19,0,1,2,16,68,...,4,7,4,NaN,3,5,"894,500","769,100","125,300",14.0%
1,2010,los angeles county,Agoura Hills,january,1,0,0,1,0,13,...,3,5,2,NaN,0,0,"4,904,800","4,267,400","637,400",13.0%
2,2010,alameda county,Alameda,january,14,0,1,7,6,147,...,19,36,18,NaN,31,34,"785,700","695,900","89,900",11.4%
3,2010,alameda county,Alameda BART,january,5,0,0,4,1,112,...,10,9,17,NaN,12,44,"785,700","695,900","89,900",11.4%
4,2010,alameda county,Alameda Co. Sheriff's Department,january,63,0,1,28,34,217,...,41,31,17,NaN,15,37,"785,700","695,900","89,900",11.4%

In [5]:
# Reorder columns
new_order = ['year', 'month', 'county'] + \
            [col for col in merged_df.columns if col not in ['year', 'month', 'county']]

merged_df = merged_df[new_order]

# Save updated file
merged_df.to_csv("merged_output_reordered.csv", index=False)

print("Columns successfully reordered.")
# Display as table
merged_df.head()

Columns successfully reordered.

,year,month,county,nciccode,violent_sum,homicide_sum,forrape_sum,robbery_sum,aggassault_sum,property_sum,...,aolarnao_sum,lt400nao_sum,lt200400nao_sum,lt200nao_sum,lt50200nao_sum,lt50nao_sum,labor force,employment,unemployment,unemp. rate
0,2010,january,san bernardino county,Adelanto,19,0,1,2,16,68,...,4,7,4,NaN,3,5,"894,500","769,100","125,300",14.0%
1,2010,january,los angeles county,Agoura Hills,1,0,0,1,0,13,...,3,5,2,NaN,0,0,"4,904,800","4,267,400","637,400",13.0%
2,2010,january,alameda county,Alameda,14,0,1,7,6,147,...,19,36,18,NaN,31,34,"785,700","695,900","89,900",11.4%
3,2010,january,alameda county,Alameda BART,5,0,0,4,1,112,...,10,9,17,NaN,12,44,"785,700","695,900","89,900",11.4%
4,2010,january,alameda county,Alameda Co. Sheriff's Department,63,0,1,28,34,217,...,41,31,17,NaN,15,37,"785,700","695,900","89,900",11.4%

In [ ]:
!pip install pandas numpy matplotlib scikit-learn statsmodels

695.23s - pydevd: Sending message related to process being replaced timed-out after 5 seconds

Requirement already satisfied: pandas in /usr/local/python/3.12.1/lib/python3.12/site-packages (3.0.1)
Requirement already satisfied: numpy in /usr/local/python/3.12.1/lib/python3.12/site-packages (2.4.2)
Collecting matplotlib
  Downloading matplotlib-3.10.8-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (52 kB)
Collecting scikit-learn
  Downloading scikit_learn-1.8.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (11 kB)
Requirement already satisfied: statsmodels in /usr/local/python/3.12.1/lib/python3.12/site-packages (0.14.6)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/codespace/.local/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Collecting contourpy>=1.0.1 (from matplotlib)
  Downloading contourpy-1.3.3-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (5.5 kB)
Collecting cycler>=0.10 (from matplotlib)
  Downloading cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.22.0 (from matplotlib)
  Downloading fonttools-4.62.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (117 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib)
  Downloading kiwisolver-1.5.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (5.1 kB)
Requirement already satisfied: packaging>=20.0 in /home/codespace/.local/lib/python3.12/site-packages (from matplotlib) (25.0)
Collecting pillow>=8 (from matplotlib)
  Downloading pillow-12.1.1-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (8.8 kB)
Collecting pyparsing>=3 (from matplotlib)
  Downloading pyparsing-3.3.2-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: scipy>=1.10.0 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from scikit-learn) (1.17.1)
Collecting joblib>=1.3.0 (from scikit-learn)
  Downloading joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting threadpoolctl>=3.2.0 (from scikit-learn)
  Downloading threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: patsy>=0.5.6 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from statsmodels) (1.0.2)
Requirement already satisfied: six>=1.5 in /home/codespace/.local/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading matplotlib-3.10.8-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (8.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.7/8.7 MB 55.3 MB/s  0:00:00
Downloading scikit_learn-1.8.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (8.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.9/8.9 MB 53.5 MB/s  0:00:00
Downloading contourpy-1.3.3-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (362 kB)
Downloading cycler-0.12.1-py3-none-any.whl (8.3 kB)
Downloading fonttools-4.62.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (5.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.0/5.0 MB 53.9 MB/s  0:00:00
Downloading joblib-1.5.3-py3-none-any.whl (309 kB)
Downloading kiwisolver-1.5.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (1.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 36.6 MB/s  0:00:00
Downloading pillow-12.1.1-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (7.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.0/7.0 MB 52.5 MB/s  0:00:00
Downloading pyparsing-3.3.2-py3-none-any.whl (122 kB)
Downloading threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Installing collected packages: threadpoolctl, pyparsing, pillow, kiwisolver, joblib, fonttools, cycler, contourpy, scikit-learn, matplotlib
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10/10 [matplotlib]0 [matplotlib]n]
Successfully installed contourpy-1.3.3 cycler-0.12.1 fonttools-4.62.1 joblib-1.5.3 kiwisolver-1.5.0 matplotlib-3.10.8 pillow-12.1.1 pyparsing-3.3.2 scikit-learn-1.8.0 threadpoolctl-3.6.0

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python3 -m pip install --upgrade pip